from django.urls import path, include
from .views import (
    dashboard,
    fetch_news,
    sentiment_chart_data,
    analyze_news_view,
    search_ticker,
    analyze_sentiment,
    custom_sentiment,
    analyze_with_insights,
    agents_run,
    agents_health,
    agents_status,
    symbol_deep_dive,
    live_ticker,
    market_history,
    quant_signals,
    quant_catalog,
    quant_backtest,
    quant_backtest_compile,
    quant_research_benchmark,
    evaluation_sentiment_accuracy,
    evaluation_latency,
    cross_domain_news,
    scanner,
    options_chain,
    intraday_trade_decision,
)

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('api/fetch-news/', fetch_news, name='fetch_news'),
    path('api/chart-data/', sentiment_chart_data, name='chart_data'),
    path('api/scanner/', scanner, name='scanner'),
    path('api/options-chain/', options_chain, name='options_chain'),
    path('api/trade/decision/', intraday_trade_decision, name='intraday_trade_decision'),
    path('api/analyze-news/', analyze_news_view, name='analyze_news'),
    path('api/search-ticker/', search_ticker, name='search_ticker'),
    path('api/analyze-sentiment/', analyze_sentiment, name='analyze_sentiment'),
    path('api/custom-sentiment/', custom_sentiment, name='custom_sentiment'),
    path('api/analyze-with-insights/', analyze_with_insights, name='analyze_with_insights'),
    path('api/agents/run/', agents_run, name='agents_run'),
    path('api/agents/health/', agents_health, name='agents_health'),
    path('api/agents/status/', agents_status, name='agents_status'),
    path('api/agents/symbol-deep-dive/', symbol_deep_dive, name='symbol_deep_dive'),
    path('api/live-ticker/', live_ticker, name='live_ticker'),
    path('api/market/<str:symbol>/history/', market_history, name='market_history'),
    path('api/quant/signals/', quant_signals, name='quant_signals'),
    path('api/quant/catalog/', quant_catalog, name='quant_catalog'),
    path('api/quant/backtest/', quant_backtest, name='quant_backtest'),
    path('api/quant/backtest/compile/', quant_backtest_compile, name='quant_backtest_compile'),
    path('api/quant/research-benchmark/', quant_research_benchmark, name='quant_research_benchmark'),
    path('api/evaluation/sentiment-accuracy/', evaluation_sentiment_accuracy, name='evaluation_sentiment_accuracy'),
    path('api/evaluation/latency/', evaluation_latency, name='evaluation_latency'),
    path('api/cross-domain/', cross_domain_news, name='cross_domain_news'),
    path('api/shock/', include('shock_predictor.urls')),
]