# Generated by Django 5.1.15 on 2026-05-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fired_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField()),
                ('cause_hypothesis', models.CharField(max_length=20)),
                ('trigger_headline', models.TextField(blank=True)),
                ('trigger_source', models.CharField(blank=True, max_length=50)),
                ('suggested_hedge', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('fired', 'Fired'), ('confirmed', 'Confirmed'), ('false_positive', 'False Positive')], default='fired', max_length=20)),
                ('eod_nifty_change', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fired_at'],
            },
        ),
        migrations.CreateModel(
            name='ShockPrecursorPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause_type', models.CharField(max_length=20, unique=True)),
                ('avg_iv_change_1hr', models.FloatField(default=0)),
                ('avg_pcr_shift', models.FloatField(default=0)),
                ('avg_vix_open', models.FloatField(default=0)),
                ('keyword_fingerprint', models.JSONField(default=list)),
                ('sample_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('index', models.CharField(default='NIFTY', max_length=20)),
                ('open_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('intraday_range', models.FloatField()),
                ('direction', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down')], max_length=4)),
                ('magnitude', models.FloatField()),
                ('cause_type', models.CharField(choices=[('policy', 'Policy / Regulatory'), ('macro', 'Macroeconomic'), ('geopolitical', 'Geopolitical'), ('technical', 'Technical / Flow'), ('corporate', 'Corporate Event'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('cause_summary', models.TextField(blank=True)),
                ('headline', models.TextField(blank=True)),
                ('pcr_before', models.FloatField(blank=True, null=True)),
                ('iv_change_pct', models.FloatField(blank=True, null=True)),
                ('fii_flow_crores', models.FloatField(blank=True, null=True)),
                ('vix_open', models.FloatField(blank=True, null=True)),
                ('precursor_signals', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('date', 'index'), name='unique_shock_date_index')],
            },
        ),
    ]
